export enum AUTH_ERROR {
  // access token
  TOKEN_INVALID = "TOKEN_INVALID_OR_MISSING",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  // refresh token
  REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID_OR_MISSING",
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED",
  // permission
  PERMISSION_DENIED = "PERMISSION_DENIED",
  // validation
  VALIDATION = "VALIDATION_ERROR",
}
