export enum ROLE_PATTERN {
  GET_LIST_ROLES = "GET_LIST_ROLES",
  GET_ROLE_BY_ID = `GET_ROLE_BY_ID`,
  CREATE_ROLE = "CREATE_ROLE",
  UPDATE_ROLE = "UPDATE_ROLE",
  DELETE_ROLE = "DELETE_ROLE",
  GET_PERMISSION_BY_KEY = "GET_PERMISSION_BY_KEY",
  INITIAL_DATABASE = "INITIAL_DATABASE",
}
