export const SERVICE_TOKEN = {
  ROLE: "ROLE_SERVICE",
  USER: "USER_SERVICE",
  AUTH: "AUTH_SERVICE",
  DEVICE: "DEVICE_SERVICE",
  TOKEN: "TOKEN_SERVICE",
  OTP: "OTP_SERVICE",
  NOTIFICATION: "NOTIFICATION_SERVICE",
  WALLET: "WALLET_SERVICE",
};
