export enum TIME_ZONE {
  VIETNAM = "Asia/Ho_Chi_Minh",
  CHINA = "Asia/Shanghai",
  JAPAN = "Asia/Tokyo",
  HONG_KONG = "Asia/Hong_Kong",
  SINGAPORE = "Asia/Singapore",
  THAILAND = "Asia/Bangkok",
  INDIA = "Asia/Kolkata",
  UTC = "Etc/UTC",
  NEW_YORK = "America/New_York",
  LOS_ANGELES = "America/Los_Angeles",
  CHICAGO = "America/Chicago",
  MEXICO_CITY = "America/Mexico_City",
  LONDON = "Europe/London",
  BERLIN = "Europe/Berlin",
  PARIS = "Europe/Paris",
  MOSCOW = "Europe/Moscow",
  SYDNEY = "Australia/Sydney",
  MELBOURNE = "Australia/Melbourne",
  ADELAIDE = "Australia/Adelaide",
  PERTH = "Australia/Perth",
  AUCKLAND = "Pacific/Auckland",
  HONOLULU = "Pacific/Honolulu",
}
